apiVersion: apps/v1
kind: Deployment
metadata:
  name: scalable-project-deployment
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      app: scalable-project-app
  template:
    metadata:
      labels:
        app: scalable-project-app
    spec:
      containers:
        - name: scalable-project-app
          image: vic20253/scalable-project-app:1.1.32 # {"$imagepolicy": "flux-system:scalable-project-app"}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: dockerhub-credentials
