apiVersion: v1
kind: Service
metadata:
  name: scalable-project-service
spec:
  selector:
    app: scalable-project-app
  ports:
    - port: 8080
      targetPort: 8080
  type: NodePort

# Déploiement : kubectl apply -f service.yaml
# Récupérer les services : kubectl get svc
# localhost:32408 = accéder au service sur un navigateur (numéro de port récupéré avec get svc)