apiVersion: v1
kind: Service
metadata:
  name: varnish-service
  namespace: default
spec:
  selector:
    app: varnish
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32630  # tu peux garder ce numéro si tu veux
  type: NodePort
