name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build image
      run: docker build -t scalable-project-app:1.0 .

    - name: Run container in background
      run: docker run -d -p 8080:8080 --name test_app scalable-project-app:1.0

    - name: Test container
      run: |
        sleep 5
        curl --fail http://localhost:8080/ || (docker logs test_app && exit 1)

    - name: Run unit tests
      run : python app_test.py
      
    - name: Stop and remove container
      run: docker rm -f test_app
